/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminCreateFormPage: typeof import('./src/components/AdminCreateFormPage.vue')['default']
    AdminFormSinglePage: typeof import('./src/components/AdminFormSinglePage.vue')['default']
    AdminFormSinglePageEntries: typeof import('./src/components/AdminFormSinglePageEntries.vue')['default']
    AdminFormsPage: typeof import('./src/components/AdminFormsPage.vue')['default']
    AdminFormStatus: typeof import('./src/components/AdminFormStatus.vue')['default']
    AdminModalFormDelete: typeof import('./src/components/AdminModalFormDelete.vue')['default']
    AdminModalFormSettings: typeof import('./src/components/AdminModalFormSettings.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PublicFormPage: typeof import('./src/components/PublicFormPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheNotifications: typeof import('./src/components/TheNotifications.vue')['default']
  }
}
